"""Gera os dados ficticios do planejador de rack.

Gera dados/equipamentos-rack.yaml (25 itens) e dados/capacidade-rack.yaml.
Saida deterministica: a mesma execucao produz sempre os mesmos bytes.

Generates the fictitious rack data as deterministic YAML files.
"""

from __future__ import annotations

from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
DADOS = RAIZ / "dados"

# nome, categoria, altura_u, peso_kg, consumo_w, fonte_redundante, circuito, fase
EQUIPAMENTOS: tuple[tuple[str, str, int, float, int, bool, int, int], ...] = (
    ("patch-panel-48p", "patch-panel", 1, 3.5, 0, False, 1, 1),
    ("patch-panel-24p-b", "patch-panel", 1, 2.8, 0, False, 1, 1),
    ("switch-acesso-48p", "switch", 1, 6.5, 180, False, 1, 1),
    ("switch-distribuicao-24p", "switch", 1, 5.0, 140, False, 2, 1),
    ("roteador-borda", "roteador", 1, 7.2, 220, True, 2, 1),
    ("servidor-aplicacao-01", "servidor", 4, 38.0, 650, True, 3, 1),
    ("servidor-aplicacao-02", "servidor", 4, 38.0, 650, True, 3, 1),
    ("ups-2kva", "ups", 4, 38.0, 60, True, 5, 1),
    ("storage-controladora", "storage", 1, 12.0, 265, True, 4, 1),
    ("kvm-16-portas", "kvm", 1, 4.5, 35, False, 5, 1),
    ("organizador-cabos-01", "organizador", 1, 1.2, 0, False, 6, 1),
    ("servidor-banco-01", "servidor", 4, 42.0, 620, True, 3, 2),
    ("servidor-banco-02", "servidor", 4, 42.0, 480, True, 4, 2),
    ("ups-1kva-b", "ups", 2, 20.0, 55, True, 6, 2),
    ("kvm-extensor", "kvm", 1, 1.8, 45, False, 4, 2),
    ("patch-panel-24p-c", "patch-panel", 1, 2.6, 0, False, 4, 2),
    ("servidor-virtualizacao-01", "servidor", 4, 40.0, 700, True, 7, 3),
    ("servidor-virtualizacao-02", "servidor", 4, 40.0, 780, True, 7, 3),
    ("switch-industrial-16p", "switch", 1, 4.2, 60, False, 2, 3),
    ("patch-panel-24p-d", "patch-panel", 1, 2.6, 0, False, 5, 3),
    ("patch-panel-24p-e", "patch-panel", 1, 2.6, 0, False, 5, 3),
    ("organizador-cabos-02", "organizador", 1, 1.2, 0, False, 6, 3),
    ("kvm-16-portas-b", "kvm", 1, 4.5, 60, False, 8, 3),
    ("libreria-fitas-24-slot", "storage", 3, 42.0, 0, False, 8, 3),
    ("modulo-bateria-ups", "ups", 2, 28.0, 0, False, 8, 2),
)

CAPACIDADE = """\
# Capacidade do rack do laboratorio. Valores ficticios.
# Fictitious lab rack capacity. No real equipment is described.
rack:
  nome: rack-lab-01
  altura_u: 42
  carga_maxima_kg: 400
  temperatura_ambiente_c: 24
  temperatura_max_saida_c: 40
  folga_recomendada: 0.20
pdu:
  nome: pdu-generica-8-circuitos
  tensao_v: 127
  circuitos: 8
  corrente_por_circuito_a: 16.0
  fases: 3
  corrente_max_por_fase_a: 16.0
  potencia_max_w: 4800
termica:
  fluxo_ar_m3h: 900
  k_termico: 0.35
  categorias_quentes:
    - servidor
    - storage
    - ups
"""


def linhas_de_equipamento() -> list[str]:
    """Monta o YAML da lista, com U inicial sequencial e sem sobreposicao.

    Builds the equipment YAML with sequential, non-overlapping start units.
    """

    linhas = [
        "# Equipamentos ficticios do rack. Gerado por tools/gerar_dados.py.",
        "# Fictitious rack equipment. Generated by tools/gerar_dados.py.",
        "equipamentos:",
    ]
    posicao = 1
    for nome, categoria, altura, peso, consumo, redundante, circuito, fase in EQUIPAMENTOS:
        linhas += [
            f"  - nome: {nome}",
            f"    categoria: {categoria}",
            f"    altura_u: {altura}",
            f"    peso_kg: {peso}",
            f"    consumo_w: {consumo}",
            f"    fonte_redundante: {'true' if redundante else 'false'}",
            f"    posicao_u: {posicao}",
            f"    circuito: {circuito}",
            f"    fase: {fase}",
        ]
        posicao += altura
    return linhas


def main() -> int:
    """Escreve os dois arquivos YAML em dados/.

    Writes both YAML files under dados/.
    """

    DADOS.mkdir(parents=True, exist_ok=True)
    equipamentos = "\n".join(linhas_de_equipamento()) + "\n"
    (DADOS / "equipamentos-rack.yaml").write_text(equipamentos, encoding="utf-8", newline="\n")
    (DADOS / "capacidade-rack.yaml").write_text(CAPACIDADE, encoding="utf-8", newline="\n")
    altura = sum(item[2] for item in EQUIPAMENTOS)
    peso = sum(item[3] for item in EQUIPAMENTOS)
    potencia = sum(item[4] for item in EQUIPAMENTOS)
    print(f"equipamentos: {len(EQUIPAMENTOS)} itens, {altura}U, {peso:.1f} kg, {potencia} W")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
